print("Please introduce yourself")
a=(input("What is your name? "))
b=(input("Where are you from? "))
c=(input("How old are you? "))
d=(input("What is your most favourite hobby? "))
e=(input("What is your favourite colour? "))
f=(input("Favourite food? "))
g=(input("Favourite drink? "))
h=(input("Favourite movie? "))
i=(input("What is the best place to hang out with friends according to you? "))
j=(input("Favourite sport? "))
k=(input("Name of father: "))
l=(input("Name of Mother: "))
m=(input("Siblings' name: (If no siblings, enter N/A) "))
n=(input("Date of Birth: "))
print("Thank you for ur cooperation!")

